name: 'Python Linting & Formatting'
description: 'Run Python code quality checks: ruff, mypy, pylint, pydocstyle'
author: 'hope0hermes'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  
  working-directory:
    description: 'Directory containing the Python project'
    required: false
    default: '.'
  
  fail-fast:
    description: 'Stop on first error'
    required: false
    default: 'true'

outputs:
  status:
    description: 'Overall linting status (passed/failed)'
    value: ${{ steps.lint.outputs.status }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install hatch

    - name: Run linting
      id: lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "Running Python linting checks..."
        
        # Run hatch lint (includes all configured linters)
        if hatch run lint:default; then
          echo "status=passed" >> $GITHUB_OUTPUT
          echo "✓ All linting checks passed"
        else
          echo "status=failed" >> $GITHUB_OUTPUT
          echo "✗ Linting checks failed"
          exit 1
        fi
