# Reusable Tests Workflow
#
# This workflow provides a complete testing pipeline for Python projects.
# It runs linting and tests with coverage reporting.
#
# Usage:
#   jobs:
#     test:
#       uses: hope0hermes/SharedWorkflows/.github/workflows/reusable-tests.yml
#       with:
#         python-version: "3.12"
#         package-name: "my_package"
#         coverage-threshold: 80

name: Reusable Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.12'

      package-name:
        description: 'Name of the package (for display purposes)'
        required: true
        type: string

      coverage-threshold:
        description: 'Minimum coverage percentage (0-100, 0 = no check)'
        required: false
        type: number
        default: 0

      run-lint:
        description: 'Whether to run linting'
        required: false
        type: boolean
        default: true

      run-tests:
        description: 'Whether to run tests'
        required: false
        type: boolean
        default: true

      working-directory:
        description: 'Directory containing the Python project'
        required: false
        type: string
        default: '.'

      pytest-args:
        description: 'Additional arguments to pass to pytest (e.g., specific test files)'
        required: false
        type: string
        default: ''

jobs:
  lint:
    if: inputs.run-lint
    runs-on: ubuntu-latest
    name: Lint ${{ inputs.package-name }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout SharedWorkflows actions
        uses: actions/checkout@v4
        with:
          repository: hope0hermes/SharedWorkflows
          ref: main
          path: .github/actions-temp

      - name: Run Python linting
        uses: .github/actions-temp/actions/python-lint
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

  test:
    if: inputs.run-tests && !contains(github.event.head_commit.message, 'release/v')
    runs-on: ubuntu-latest
    name: Test ${{ inputs.package-name }}
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - name: Checkout SharedWorkflows actions
        uses: actions/checkout@v4
        with:
          repository: hope0hermes/SharedWorkflows
          ref: main
          path: .github/actions-temp

      - name: Run Python tests
        uses: .github/actions-temp/actions/python-test
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}
          coverage-threshold: ${{ inputs.coverage-threshold }}
          upload-coverage: 'true'
          pytest-args: ${{ inputs.pytest-args }}

# Concurrency control:
# - If you push multiple commits quickly to the same PR, old test runs are cancelled
# - Saves CI resources by not running outdated code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
